# Generated by Django 5.1.2 on 2024-10-26 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_sellerform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SellerForm',
            new_name='Seller',
        ),
    ]
